# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  # override - new property - has to go before FileSetBehaviour
  property :mets_extracted,
           predicate: ::RDF::URI('http://example.com/hull_culture#mets_extracted'),
           class_name: 'Boolean',
           multiple: false

  # override - additional file metadata - before FileSetBehaviour
  include ::Archivematica

  include ::Hyrax::FileSetBehavior

  # override - indexing additional file metadata
  self.indexer = FileSetIndexerExtended

  # override - add different file uses
  directly_contains_one :preservation_master_file, through: :files, type: ::RDF::URI('http://pcdm.org/use#PreservationMasterFile'), class_name: 'Hydra::PCDM::File'
  directly_contains_one :sip_file, through: :files, type: ::RDF::URI('http://london.ac.uk/use#SIPFile'), class_name: 'Hydra::PCDM::File'

  # override - enable all terms
  self.characterization_terms = %i[
    bit_depth
    byte_order
    capture_device
    channels
    character_count
    character_set
    color_map
    color_space
    compression
    creator
    data_format
    date_created
    duration
    exif_version
    file_format
    file_size
    file_title
    fits_version
    format_label
    frame_rate
    gps_timestamp
    graphics_count
    height
    image_producer
    language
    latitude
    line_count
    longitude
    markup_basis
    markup_language
    mime_type
    offset
    orientation
    original_checksum
    page_count
    paragraph_count
    profile_name
    profile_version
    sample_rate
    scanning_software
    table_count
    valid
    well_formed
    width
    word_count
  ]

  # override - add characterization_terms to sip_terms
  self.sip_terms += characterization_terms
end
